import { DriveFile } from "@/types/drive";

export const MOCK_ROOT_FILES: DriveFile[] = [
  {
    id: "folder-proyek-q3",
    name: "Laporan Proyek Kuartal 3 - 2026",
    mimeType: "application/vnd.google-apps.folder",
    modifiedTime: "2026-09-18T10:45:00Z",
    createdTime: "2026-08-01T08:00:00Z",
    shared: true,
    owners: [{ displayName: "Budi Santoso", emailAddress: "budi@example.com" }],
    webViewLink: "https://drive.google.com/drive/folders/folder-proyek-q3",
  },
  {
    id: "folder-desain-ui",
    name: "Aset & Dokumentasi Desain UI",
    mimeType: "application/vnd.google-apps.folder",
    modifiedTime: "2026-09-19T14:20:00Z",
    createdTime: "2026-07-15T09:30:00Z",
    shared: false,
    owners: [{ displayName: "Saya", me: true }],
    webViewLink: "https://drive.google.com/drive/folders/folder-desain-ui",
  },
  {
    id: "folder-arsip-keuangan",
    name: "Arsip Keuangan & Tagihan",
    mimeType: "application/vnd.google-apps.folder",
    modifiedTime: "2026-09-15T11:10:00Z",
    createdTime: "2026-06-10T12:00:00Z",
    shared: true,
    owners: [{ displayName: "Fintech Finance", emailAddress: "finance@example.com" }],
    webViewLink: "https://drive.google.com/drive/folders/folder-arsip-keuangan",
  },
  {
    id: "file-proposal-bisnis-2026",
    name: "Proposal_Pengembangan_Sistem_2026.docx",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 2450000, // 2.45 MB
    modifiedTime: "2026-09-20T16:30:00Z",
    createdTime: "2026-09-02T10:00:00Z",
    shared: false,
    owners: [{ displayName: "Saya", me: true }],
    webViewLink: "https://docs.google.com/document/d/file-proposal-bisnis-2026",
  },
  {
    id: "file-anggaran-tahunan",
    name: "Rekapitulasi_Anggaran_Tahunan.xlsx",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 8430000, // 8.43 MB
    modifiedTime: "2026-09-19T08:15:00Z",
    createdTime: "2026-08-10T14:20:00Z",
    shared: true,
    owners: [{ displayName: "Siti Rahma", emailAddress: "siti@example.com" }],
    webViewLink: "https://docs.google.com/spreadsheets/d/file-anggaran-tahunan",
  },
  {
    id: "file-slide-pitch-deck",
    name: "Investor_Pitch_Deck_Antigravity.pptx",
    mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 19800000, // 19.8 MB
    modifiedTime: "2026-09-17T09:00:00Z",
    createdTime: "2026-08-25T11:00:00Z",
    shared: true,
    owners: [{ displayName: "Saya", me: true }],
    webViewLink: "https://docs.google.com/presentation/d/file-slide-pitch-deck",
  },
  {
    id: "file-panduan-arsitektur-pdf",
    name: "Whitepaper_Arsitektur_Cloud_Native.pdf",
    mimeType: "application/pdf",
    size: 5120000, // 5.12 MB
    modifiedTime: "2026-09-14T13:45:00Z",
    createdTime: "2026-07-20T15:30:00Z",
    shared: false,
    owners: [{ displayName: "Saya", me: true }],
    webViewLink: "https://drive.google.com/file/d/file-panduan-arsitektur-pdf",
  },
  {
    id: "file-mockup-dashboard-png",
    name: "Mockup_Dashboard_WhiteSmoke_v2.png",
    mimeType: "image/png",
    size: 3840000, // 3.84 MB
    modifiedTime: "2026-09-20T17:10:00Z",
    createdTime: "2026-09-19T09:00:00Z",
    shared: false,
    owners: [{ displayName: "Saya", me: true }],
    webViewLink: "https://drive.google.com/file/d/file-mockup-dashboard-png",
  },
  {
    id: "file-demo-video-mp4",
    name: "Walkthrough_Aplikasi_NextJS15.mp4",
    mimeType: "video/mp4",
    size: 142000000, // 142 MB
    modifiedTime: "2026-09-12T19:00:00Z",
    createdTime: "2026-09-10T18:00:00Z",
    shared: true,
    owners: [{ displayName: "Rian Pratama", emailAddress: "rian@example.com" }],
    webViewLink: "https://drive.google.com/file/d/file-demo-video-mp4",
  },
  {
    id: "file-bundle-source-zip",
    name: "Source_Code_Backup_September.zip",
    mimeType: "application/zip",
    size: 67400000, // 67.4 MB
    modifiedTime: "2026-09-08T11:20:00Z",
    createdTime: "2026-09-08T11:00:00Z",
    shared: false,
    owners: [{ displayName: "Saya", me: true }],
    webViewLink: "https://drive.google.com/file/d/file-bundle-source-zip",
  },
  {
    id: "file-kontrak-kerja-pdf",
    name: "Surat_Perjanjian_Kerjasama_Vendor.pdf",
    mimeType: "application/pdf",
    size: 1820000, // 1.82 MB
    modifiedTime: "2026-09-05T14:30:00Z",
    createdTime: "2026-09-01T10:15:00Z",
    shared: true,
    owners: [{ displayName: "Legal Division", emailAddress: "legal@example.com" }],
    webViewLink: "https://drive.google.com/file/d/file-kontrak-kerja-pdf",
  },
  {
    id: "file-google-doc-catatan",
    name: "Notula_Rapat_Strategis_Google_Drive.gdoc",
    mimeType: "application/vnd.google-apps.document",
    size: 45000,
    modifiedTime: "2026-09-21T04:10:00Z",
    createdTime: "2026-09-21T02:00:00Z",
    shared: true,
    owners: [{ displayName: "Saya", me: true }],
    webViewLink: "https://docs.google.com/document/d/file-google-doc-catatan",
  },
];

export const MOCK_SUBFOLDER_FILES: Record<string, DriveFile[]> = {
  "folder-proyek-q3": [
    {
      id: "subfile-timeline-q3",
      name: "Timeline_Eksekusi_Proyek_Q3.xlsx",
      mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      size: 4150000,
      modifiedTime: "2026-09-18T10:45:00Z",
      parents: ["folder-proyek-q3"],
      shared: true,
      owners: [{ displayName: "Budi Santoso" }],
      webViewLink: "https://docs.google.com/spreadsheets/d/subfile-timeline-q3",
    },
    {
      id: "subfile-status-sprint",
      name: "Catatan_Sprint_Review_12.docx",
      mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      size: 1120000,
      modifiedTime: "2026-09-17T16:20:00Z",
      parents: ["folder-proyek-q3"],
      shared: false,
      owners: [{ displayName: "Saya", me: true }],
      webViewLink: "https://docs.google.com/document/d/subfile-status-sprint",
    },
    {
      id: "subfile-arsip-asset-q3",
      name: "Diagram_Arsitektur_Sistem_Q3.png",
      mimeType: "image/png",
      size: 2850000,
      modifiedTime: "2026-09-16T12:00:00Z",
      parents: ["folder-proyek-q3"],
      shared: true,
      owners: [{ displayName: "Saya", me: true }],
      webViewLink: "https://drive.google.com/file/d/subfile-arsip-asset-q3",
    },
  ],
  "folder-desain-ui": [
    {
      id: "subfile-wireframe-figma",
      name: "Export_Figma_Komponen_UI.pdf",
      mimeType: "application/pdf",
      size: 15400000,
      modifiedTime: "2026-09-19T14:20:00Z",
      parents: ["folder-desain-ui"],
      shared: false,
      owners: [{ displayName: "Saya", me: true }],
      webViewLink: "https://drive.google.com/file/d/subfile-wireframe-figma",
    },
    {
      id: "subfile-palet-warna-whitesmoke",
      name: "Token_Color_WhiteSmoke_Guide.pdf",
      mimeType: "application/pdf",
      size: 3200000,
      modifiedTime: "2026-09-18T09:00:00Z",
      parents: ["folder-desain-ui"],
      shared: false,
      owners: [{ displayName: "Saya", me: true }],
      webViewLink: "https://drive.google.com/file/d/subfile-palet-warna-whitesmoke",
    },
    {
      id: "subfile-icons-pack",
      name: "Lucide_Custom_Icons_Pack.zip",
      mimeType: "application/zip",
      size: 8900000,
      modifiedTime: "2026-09-15T10:00:00Z",
      parents: ["folder-desain-ui"],
      shared: false,
      owners: [{ displayName: "Saya", me: true }],
      webViewLink: "https://drive.google.com/file/d/subfile-icons-pack",
    },
  ],
  "folder-arsip-keuangan": [
    {
      id: "subfile-invoice-september",
      name: "Invoice_Pembayaran_Server_September.pdf",
      mimeType: "application/pdf",
      size: 950000,
      modifiedTime: "2026-09-15T11:10:00Z",
      parents: ["folder-arsip-keuangan"],
      shared: true,
      owners: [{ displayName: "Fintech Finance" }],
      webViewLink: "https://drive.google.com/file/d/subfile-invoice-september",
    },
    {
      id: "subfile-laporan-pajak",
      name: "SPT_Pajak_Badan_2025.pdf",
      mimeType: "application/pdf",
      size: 4200000,
      modifiedTime: "2026-08-30T15:00:00Z",
      parents: ["folder-arsip-keuangan"],
      shared: true,
      owners: [{ displayName: "Fintech Finance" }],
      webViewLink: "https://drive.google.com/file/d/subfile-laporan-pajak",
    },
  ],
};

export const MOCK_FOLDER_NAMES: Record<string, string> = {
  root: "My Drive",
  "folder-proyek-q3": "Laporan Proyek Kuartal 3 - 2026",
  "folder-desain-ui": "Aset & Dokumentasi Desain UI",
  "folder-arsip-keuangan": "Arsip Keuangan & Tagihan",
};
